import type { NextConfig } from "next";

const nextConfig: NextConfig = {
    env: {
      NEXT_PRIVATE_SANITY_API_VERSION: process.env.NEXT_PRIVATE_SANITY_API_VERSION,
      NEXT_PRIVATE_SANITY_PROJECT_ID: process.env.NEXT_PRIVATE_SANITY_PROJECT_ID,
      NEXT_PRIVATE_SANITY_DATASET: process.env.NEXT_PRIVATE_SANITY_DATASET,
      NEXT_PRIVATE_SERVICE_ID: process.env.NEXT_PRIVATE_SANITY_DATASET,
      NEXT_PRIVATE_TEMPLATE_ID: process.env.NEXT_PRIVATE_TEMPLATE_ID,
      NEXT_PRIVATE_USER_ID: process.env.NEXT_PRIVATE_USER_ID,
      SANITY_STUDIO_DATASET: process.env.SANITY_STUDIO_DATASET,
      SANITY_STUDIO_PROJECT_ID: process.env.SANITY_STUDIO_PROJECT_ID
    }
};

export default nextConfig;