import { EditorState } from "./components/types";
export const titleData: EditorState[] = [
  {
    name: "Select A Title Sequence",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fourth_title_card.png",
    alt: "Fourth Doctor Title Vortex",
    font: "var(--font-della-respira)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
  },
  {
    name: "Second Doctor (1967 - 1969)",
    textAllCaps: "uppercase",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/second_title.png",
    alt: "Second Doctor Title Vortex",
    font: "var(--font-eurostile)",
    fontSize: 24,
    textShadow: "1px 1px 2px black",
  },
  {
    name: "Third Doctor (1970 - 1973)",
    textAllCaps: "uppercase",
    writerCredit: false,
    color: "#C7BF12",
    background: "/images/drWhoTitles/third_title_card.png",
    alt: "Third Doctor Title Vortex",
    font: "var(--font-futuraBold)",
    fontSize: 32,
    textShadow: "1px 1px 2px black",
  },
  {
    name: "Third Doctor (1974)",
    textAllCaps: "uppercase",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/third_title_74.png",
    alt: "Third Doctor Title Vortex",
    font: "var(--font-futuraXtaBold)",
    fontSize: 32,
    textShadow: "1px 1px 2px black",
  },
  {
    name: "Fourth Doctor (1974 - 1976)",
    textAllCaps: "uppercase",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fourth_title_card.png",
    alt: "Fourth Doctor Title Vortex",
    font: "var(--font-futuraXtaBold)",
    fontSize: 30,
    textShadow: "1px 1px 2px black",
  },
  {
    name: "Fourth Doctor (1976 - 1980)",
    textAllCaps: "uppercase",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fourth_title_card.png",
    alt: "Fourth Doctor Title Vortex",
    font: "var(--font-della-respira)",
    fontSize: 30,
    textShadow: "1px 1px 2px black",
  },
  {
    name: "Fourth and Fifth Doctor (1980 - 1984)",
    writerCredit: false,
    background: "/images/drWhoTitles/fifth_title.png",
    alt: "Fifth Doctor Title Starscape",
    font: "var(--font-optione)",
    fontSize: 36,
    outline: "0.5px",
    outlineColour: "white",
  },
  {
    name: "Sixth Doctor (1984 - 1986)",
    writerCredit: false,
    background: "/images/drWhoTitles/sixth_title.png",
    alt: "Sixth Doctor Title Starscape",
    font: "var(--font-optione)",
    fontSize: 36,
    outline: "0.5px",
    outlineColour: "white",
  },
  {
    name: "Seventh Doctor (1987 - 1989)",
    textAllCaps: "uppercase",
    writerCredit: true,
    color: "#ffff",
    background: "/images/drWhoTitles/seventh_title.png",
    alt: "Seventh Doctor Title Card",
    font: "var(--font-univers)",
    fontSize: 18,
    textShadow: "1px 1px 2px black",
    top: "70%",
  },
  {
    name: "Ninth and Tenth Doctors (2005 - 2010)",
    textAllCaps: "uppercase",
    writerCredit: true,
    color: "#ffff",
    background: "/images/drWhoTitles/tenth_title.png",
    alt: "Tenth Doctor Title Vortex",
    font: "var(--font-futuraBook)",
    fontSize: 20,
    textShadow: "1px 1px 2px black",
    fontWeight: 100,
  },
  {
    name: "Eleventh Doctor (2010 - 2011)",
    textAllCaps: "uppercase",
    writerCredit: true,
    color: "#ffff",
    background: "/images/drWhoTitles/eleventh_one.png",
    alt: "Eleventh Doctor Title Vortex",
    font: "var(--font-sfmovie)",
    fontSize: 24,
    textShadow: "1px 1px 2px black",
    letterSpacing: 10,
    top: "70%",
  },
  {
    name: "Eleventh Doctor (2012 - 2013)",
    textAllCaps: "uppercase",
    writerCredit: true,
    color: "#ffff",
    background: "/images/drWhoTitles/eleventh_two.png",
    alt: "Eleventh Doctor Title Vortex",
    font: "var(--font-contaxpro)",
    fontSize: 18,
    textShadow: "1px 1px 2px black",
    top: "30%",
    fontWeight: 100,
  },
  {
    name: "Twelth Doctor (2014 - 2017)",
    writerCredit: true,
    textAllCaps: "capitalize",
    color: "#ffff",
    background: "/images/drWhoTitles/twelth_title.png",
    alt: "Twelfth Doctor Title Vortex",
    font: "var(--font-heroic)",
    fontSize: 20,
    textShadow: "1px 1px 2px black",
    width: "50%",
  },
  {
    name: "Thirteenth Doctor (2018 - 2022)",
    textAllCaps: "uppercase",
    writerCredit: true,
    color: "transparent",
    textBackground:
      "linear-gradient(108deg,rgba(245, 233, 182, 1) 0%, rgba(245, 233, 182, 1) 18%, rgba(122, 62, 66, 1) 25%, rgba(245, 233, 182, 1) 32%, rgba(245, 233, 182, 1) 68%, rgba(122, 62, 66, 1) 75%, rgba(245, 233, 182, 1) 82%)",
    background: "/images/drWhoTitles/thirteenth_title.png",
    alt: "Thirteenth Doctor Title Card",
    font: "var(--font-axiformaReg)",
    fontSize: 20,
    fontWeight: "400",
    textShadow: "1px 1px 2px black",
    width: "90%",
    top: "45%",
    brightness: "brightness(1.5)",
  },
  {
    name: "Fourteenth and Fifteenth Doctors (2023 - 2025)",
    writerCredit: true,
    color: "#ffff",
    background: "/images/drWhoTitles/fifteenth.png",
    alt: "Fifteenth Doctor Title Vortex",
    font: "var(--font-displaymedium)",
    fontSize: 16,
    textShadow: "1px 1px 2px black",
    top: "40%",
  },
];
