import { EditorState } from "./components/types";
export const titleData: EditorState[] = [
  {
    name: "Select A Title Sequence",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fourth_title_card.png",
    alt: "Fourth Doctor Title Vortex",
    font: "var(--font-della-respira)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  {
    name: "Second Doctor (1967 - 1969)",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/second_title.png",
    alt: "Second Doctor Title Vortex",
    font: "var(--font-eurostile)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  {
    name: "Third Doctor (1970 - 1973)",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#C7BF12",
    background: "/images/drWhoTitles/third_title_card.png",
    alt: "Third Doctor Title Vortex",
    font: "var(--font-futuraBold)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  //   {
  //     name: "Third Doctor (1974)",
  //     text: "Doctor Who Title Generator",
  //    writerCredit: false,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/third_title_card.png",
  //     alt: "Third Doctor Title Vortex",
  //     font: "var(--font-futuraXtaBold)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
  {
    name: "Fourth Doctor (1974 - 1976)",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fourth_title_card.png",
    alt: "Fourth Doctor Title Vortex",
    font: "var(--font-futuraXtaBold)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  {
    name: "Fourth Doctor (1976 - 1980)",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fourth_title_card.png",
    alt: "Fourth Doctor Title Vortex",
    font: "var(--font-della-respira)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  {
    name: "Fourth and Fifth Doctor (1980 - 1984)",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/fifth_title.png",
    alt: "Fifth Doctor Title Starscape",
    font: "var(--font-optione)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  //   {
  //     name: "Sixth Doctor (1984 - 1986)",
  //     text: "Doctor Who Title Generator",
  //    writerCredit: false,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/fifth_title.png",
  //     alt: "Fifth Doctor Title Starscape",
  //     font: "var(--font-optione)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
  //   {
  //     name: "Seventh Doctor (1987 - 1989)",
  //     text: "Doctor Who Title Generator",
  // writerCredit: true,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/fifth_title.png",
  //     alt: "Fifth Doctor Title Starscape",
  //     font: "var(--font-optione)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
  {
    name: "Ninth and Tenth Doctors (2005 - 2010)",
    text: "Doctor Who Title Generator",
    writerCredit: true,
    color: "#ffff",
    background: "/images/drWhoTitles/tenth_title.png",
    alt: "Tenth Doctor Title Vortex",
    font: "var(--font-futuraBook)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  //   {
  //     name: "Eleventh Doctor (2005 - 2010)",
  //     text: "Doctor Who Title Generator",
  // writerCredit: true,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/tenth.png",
  //     alt: "Tenth Doctor Title Vortex",
  //     font: "var(--font-futuraBook)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
  //   {
  //     name: "Eleventh Doctor (2005 - 2010)",
  //     text: "Doctor Who Title Generator",
  // writerCredit: true,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/tenth.png",
  //     alt: "Tenth Doctor Title Vortex",
  //     font: "var(--font-futuraBook)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
  //   {
  //     name: "Twelth Doctor (2005 - 2010)",
  //     text: "Doctor Who Title Generator",
  //    writerCredit: true,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/tenth.png",
  //     alt: "Tenth Doctor Title Vortex",
  //     font: "var(--font-futuraBook)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
  {
    name: "Thirteenth Doctor (2018 - 2022)",
    text: "Doctor Who Title Generator",
    writerCredit: false,
    color: "#ffff",
    background: "/images/drWhoTitles/thirteenth_title.png",
    alt: "Thirteenth Doctor Title Card",
    font: "var(--font-axiformaReg)",
    fontSize: 36,
    textShadow: "1px 1px 2px black",
    subtitleOffset: 0,
    effect: null,
    generating: false,
  },
  //   {
  //     name: "Fourteenth and Fifteenth Doctors (2023 - 2025)",
  //     text: "Doctor Who Title Generator",
  //    writerCredit: false,
  //     color: "#ffff",
  //     background: "/images/drWhoTitles/fourth_title_card.png",
  //     alt: "Fourth Doctor Title Vortex",
  //     font: "var(--font-della-respira)",
  //     fontSize: 36,
  //     textShadow: "1px 1px 2px black",
  //     subtitleOffset: 0,
  //     effect: null,
  //     generating: false,
  //   },
];
